export enum Fields {
    artist = "ARTIST",
    artistTranslit = "ARTISTTRANSLIT",
    background = "BACKGROUND",
    banner = "BANNER",
    bgChanges = "BGCHANGES",
    bpms = "BPMS",
    cdTitle = "CDTITLE",
    credit = "CREDIT",
    genre = "GENRE",
    keySounds = "KEYSOUNDS",
    lyricsPath = "LYRICSPATH",
    music = "MUSIC",
    notes = "NOTES",
    offset = "OFFSET",
    sampleLength = "SAMPLELENGTH",
    sampleStart = "SAMPLESTART",
    selectable = "SELECTABLE",
    stops = "STOPS",
    subtitle = "SUBTITLE",
    subtitleTranslit = "SUBTITLETRANSLIT",
    title = "TITLE",
    titleTranslit = "TITLETRANSLIT",
}
