FROM nginx:alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /app/
COPY client/img/noteskins noteskins/

# Remove the original image files (.psd)
RUN find noteskins/ -name __original__ | xargs rm -rf

COPY dist/ .
