name: Build, Test, Push, Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-test-push:
    name: Build, Test, Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: yarn lint && yarn format-check

      - name: Run tests
        run: yarn test

      - name: Build image
        run: ./tasks.sh build

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to DockerHub
        if: github.event_name == 'push'
        run: docker push openchart/nginx

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-test-push
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update known_hosts
        run: |
          set +e
          for i in {1..10}; do
            ssh-keyscan openchart.io >> ~/.ssh/known_hosts \
              && exit 0
            echo "ssh-keyscan failed, retrying..."
            sleep 2
          done
          exit 1

      - name: Setup Docker context
        run: |
          docker context create --docker host=${{ secrets.DEPLOY_HOST }} openchart
          docker context use openchart

      - name: Deploy
        run: |
          set +e
          for i in {1..10}; do
            docker stack deploy -c docker/docker-compose.yml openchart \
              && exit 0
            echo "deploy failed, retrying..."
            sleep 2
          done
          exit 1
