name: Check
on:
  pull_request:

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Run linter and check formatting
        run: yarn lint && yarn format-check

      - name: Check syntax/types
        run: yarn tsc --noEmit

      - name: Run tests
        run: yarn test --reporter min
