name: Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: checks

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: ./tasks.sh build

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to DockerHub
        run: docker push openchart/nginx

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update known_hosts
        run: ssh-keyscan openchart.io >> ~/.ssh/known_hosts

      - name: Setup Docker context
        run: |
          docker context create --docker host=${{ secrets.DEPLOY_HOST }} openchart
          docker context use openchart

      - name: Deploy
        run: docker stack deploy -c docker/docker-compose.yml openchart
